plugins:
  remark-behead:
    after: null
    depth: 1
templateDir: .paperist/ejs
imageConfigs:
  keepaspectratio: true
  width: 0.9\linewidth
  height: 0.25\paperheight
documentInfo:
  fontpreset: sourcehan-otc
  flags:
    interaction: false
    acknowledgment: false
    appendix: false
    english:
      author: false
      abstract: false
  title:
    ja: |
      InvisibleFlick: 小型タッチスクリーン端末における\\キートップが透明な日本語入力キーボード
  date:
    year: 2019
    month: 3
  keywords: []
  affiliates:
    - id: Meiji
      isPresent: false
      name:
        ja: 明治大学
        en: Meiji University
  authors:
    - affiliateIds:
        - Meiji
      name:
        ja: 鳥山 らいか
        en: Raika Toriyama
    - affiliateIds:
        - Meiji
      name:
        ja: 宮下 芳明
        en: Homei Miyashita
  documentclass: jsbook
  documentoptions:
    - uplatex
    - english
    - a4paper
    - 10pt
    - oneside
    - onecolumn
    - openany
